Add Feature/freeze
belivvr/hubs pull request #27
Opened 2022-09-23 06:36 UTC by jeus0630

## DOING
- 자리 고정 추가(움직임 제어)
- 아래의 코드 삽입으로 관리자 설정 가능
```js
window.XRCLOUD = {
    permissions: {
        freeze: true
    }
}
```

## NOTE
- PC 일 경우에는 wasd 와 Arrow keys의 이벤트를 막음
- 모바일 일 경우에는 조이스틱 컨트롤러를 스타일로 숨김
    - 컨트롤러 자체를 없앴다 생성시켰다 하게끔 코딩할 경우 유저가 계속 클릭시 브라우저가 다운됨
- *****VR***을 사용할 경우에는 어떻게 처리해야 하는지..**    
## UI
<img width="443" alt="image" src="https://user-images.githubusercontent.com/75295915/191903777-87e073e2-a322-4064-8835-cd97b70be49b.png">
<img width="182" alt="image" src="https://user-images.githubusercontent.com/75295915/191904023-ccf56d2d-9203-4219-b309-7d1ba5a50764.png">

<img width="179" alt="image" src="https://user-images.githubusercontent.com/75295915/191903974-2a4e686c-2856-4486-9ca6-ceb29fcb8f6f.png">

2022-09-23 06:38 UTC, juunini commented
ㅋㅋㅋ 자꾸 길이졐ㅋㅋㅋㅋ

2022-09-23 06:44 UTC, juunini requested changes
좀 더 근본적인 부분의 코드를 살펴보세요

2022-09-26 07:54 UTC, jeus0630 commented
모바일에서는 write()에 패드 컨트롤러가 매핑이 안되어 있어서 수정한 코드와 기존 코드는 그대로 가져갔습니다.

2022-09-26 08:06 UTC, juunini commented on src/systems/userinput/userinput.js
> +    });
음 이거 잘 찾으셨네요.
코드를 좀 더 자세히 보고 제가 수정할 부분을 말씀드릴게요.

2022-09-26 08:07 UTC, jeus0630 commented on src/systems/userinput/userinput.js
> +    });
어뭐야 console.log()가 들어갔네

2022-09-28 04:20 UTC, merged